name: Sync Upstream

permissions: write-all

on: [workflow_dispatch]

jobs:
  sync-upstream-vantom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: vantom-14
          fetch-depth: 0
      - name: Sync
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: vantoman/kernel_xiaomi_sm6150
          upstream-branch: 14
          branch: vantom-14
